/*
 * generated by Xtext
 */
package com.itemis.mobile.physis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PhysisUiModule extends com.itemis.mobile.physis.ui.AbstractPhysisUiModule {
	public PhysisUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
