/*
 * generated by Xtext
 */
package com.itemis.mobile.physis;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PhysisRuntimeModule extends com.itemis.mobile.physis.AbstractPhysisRuntimeModule {

}
