/*
* generated by Xtext
*/
package com.itemis.mobile.physis.ui.contentassist;

import com.itemis.mobile.physis.ui.contentassist.AbstractPhysisProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PhysisProposalProvider extends AbstractPhysisProposalProvider {

}
