/*
* generated by Xtext
*/
package com.itemis.mobile.physis.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class PhysisTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
