/*
* generated by Xtext
*/
package com.itemis.mobile.physis.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PhysisOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
