#!/usr/bin/env bash

scriptDir=$(dirname $0)
modelPath=$1
targetDir=$2
if [ -z "$modelPath" ]
then
	modelPath="."
fi

if [ -z "$targetDir" ]
then
	targetDir="output"
fi

# (ASCII art generated by http://www.network-science.de/ascii/)
echo "        ______                _____        "
echo "___________  /______  ___________(_)_______"
echo "___  __ \_  __ \_  / / /_  ___/_  /__  ___/"
echo "__  /_/ /  / / /  /_/ /_(__  )_  / _(__  ) "
echo "_  .___//_/ /_/_\__, / /____/ /_/  /____/  "
echo "/_/            /____/                      "
echo "physis 0.1"
echo "(c) 2011 Peter Friese / itemis mobile"
echo "Running physis generator..."
java -jar $scriptDir/physis.jar workflow.PhysisGenerator -pmodelPath=$modelPath -ptargetDir=$targetDir