/*
* generated by Xtext
*/
package com.itemis.mobile.physis.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.itemis.mobile.physis.services.PhysisGrammarAccess;

public class PhysisParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PhysisGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.itemis.mobile.physis.parser.antlr.internal.InternalPhysisParser createParser(XtextTokenStream stream) {
		return new com.itemis.mobile.physis.parser.antlr.internal.InternalPhysisParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PhysisGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PhysisGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
